# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../00_core.ipynb 3
def say_hello(to: str) -> str:
    "Say Hello to somebody"
    return f"Hello {to}!"

# %% ../00_core.ipynb 7
def foo(): pass
